Repository Ragarnoy/GBMU, pull requests merged in 2021-12, with the labels that each got.

#386 Implement opcode ADD SP i8
  gb-cpu/src/microcode/arithmetic.rs
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/math.rs
Labels: CPU, Opcode

#389 Feature/dgb joypad
  gb-dbg/src/debugger/status_bar.rs
Labels: Debug

#397 Feature/load mbc from dialog
  src/context.rs
  src/custom_event.rs
  src/main.rs
  src/ui.rs
Labels: ROM, GUI

#404 Feature/rework parsing breakpoint expr
  gb-dbg/src/debugger/breakpoints.rs
  gb-dbg/src/debugger/breakpoints/breakpoint.rs
  gb-dbg/src/debugger/breakpoints/breakpoint_expression.rs
  gb-dbg/src/debugger/breakpoints/parser.rs
  gb-dbg/src/debugger/breakpoints/test_parser.rs
Labels: Debug, refactor

#399 Bugfix/fix joypad fire
  gb-joypad/Cargo.toml
  gb-joypad/src/input.rs
  gb-joypad/src/joypad.rs
  gb-joypad/src/lib.rs
  gb-joypad/src/register.rs
  gb-joypad/src/utils.rs
Labels: Bug, Inputs

#413 Opcode rework - jump
  gb-cpu/src/microcode/fetch.rs
Labels: CPU, Opcode

#401 add table for all curently available features
  README.md
Labels: Documentation

#411 Feature/rework microcontroller
  gb-clock/src/clock.rs
  gb-cpu/src/lib.rs
  gb-cpu/src/microcode.rs
  gb-cpu/src/microcode/arithmetic.rs
  gb-cpu/src/microcode/bitwise.rs
  gb-cpu/src/microcode/condition.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/dec.rs
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/fetch_cb.rs
  gb-cpu/src/microcode/flag.rs
  gb-cpu/src/microcode/inc.rs
  gb-cpu/src/microcode/interrupts.rs
  gb-cpu/src/microcode/jump.rs
  gb-cpu/src/microcode/logic.rs
  gb-cpu/src/microcode/opcode.rs
  gb-cpu/src/microcode/push.rs
  gb-cpu/src/microcode/read.rs
  gb-cpu/src/microcode/utils.rs
  gb-cpu/src/microcode/write.rs
  gb-cpu/tests/bdd.rs
  gb-dbg/src/debugger.rs
  gb-dbg/src/debugger/disassembler.rs
  gb-roms/src/controllers.rs
Labels: CPU, Opcode

#422 joypad mode inversion fix
  gb-joypad/src/joypad.rs
Labels: Bug, Inputs

#402 Feature/put jump log into feature
  README.md
  gb-cpu/Cargo.toml
  gb-cpu/src/microcode/jump.rs
Labels: Debug, refactor

#406 Feature/dgb breakpoint upgrade
  gb-dbg/src/debugger.rs
  gb-dbg/src/debugger/breakpoints.rs
  gb-dbg/src/debugger/breakpoints/breakpoint.rs
  gb-dbg/src/debugger/breakpoints/breakpoint_expression.rs
  gb-dbg/src/debugger/breakpoints/evaluation.rs
  gb-dbg/src/debugger/breakpoints/parser.rs
  gb-dbg/src/debugger/breakpoints/test_parser.rs
  gb-dbg/src/lib.rs
Labels: Debug

#427 Feature/skip bios
  .lsp.config.json
  Cargo.toml
  gb-bus/Cargo.toml
  gb-bus/src/address.rs
  gb-bus/src/generic.rs
  gb-bus/src/generic/panic.rs
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/io_reg_constant.rs
  gb-bus/src/io_reg_constant_color.rs
  gb-bus/src/lib.rs
  gb-cpu/src/cpu.rs
  gb-ppu/Cargo.toml
  gb-ppu/src/registers/ppu_registers.rs
  gb-roms/src/controllers/bios_wrapper.rs
  src/context.rs
Labels: Bios

#428 Bugfix/feature registers logs
  gb-cpu/src/microcode/controller.rs
Labels: Bug, refactor

#429 Bugfix/wrong pop af
  gb-cpu/src/microcode/write.rs
Labels: Bug, CPU

#410 add method to know if cartridge is cgb compatible
  gb-roms/src/header.rs
Labels: ROM

#407 Feature/bankable storage
  gb-bus/src/generic.rs
  gb-bus/src/generic/bankable.rs
  gb-bus/src/generic/bankable_dyn.rs
  gb-bus/src/working_ram.rs
Labels: refactor

#424 Feature/bump 1.57.0
  .github/workflows/rust.yml
  README.md
  gb-test/src/bus.rs
Labels: refactor

#438 Bugfix/half carry add adc
  gb-cpu/src/microcode/arithmetic.rs
  gb-cpu/src/microcode/dec.rs
  gb-cpu/src/microcode/inc.rs
  gb-cpu/src/microcode/logic.rs
  gb-cpu/src/microcode/math.rs
Labels: Bug, refactor

#435 correct typo feature
  gb-bus/src/address_bus.rs
  gb-bus/src/io_reg_bus.rs
Labels: Bug, Architecture

#436 Feature/rework bus macro
  gb-bus/src/address_bus.rs
  gb-bus/src/io_reg_bus.rs
Labels: BUS, refactor

#448 Don't transform color twice.
  gb-ppu/src/sprite.rs
Labels: Bug, Display

#444 fix ld16sp loading value in incorrect order
  gb-cpu/src/microcode/write.rs
Labels: Bug, CPU

#446 Bugfix/addspi8
  gb-cpu/src/microcode/arithmetic.rs
  gb-cpu/src/microcode/bitwise.rs
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/math.rs
Labels: Bug, CPU, Opcode

#449 Bugfix/timer inc
  .gitignore
  Cargo.lock
  debug/registers_logs/bootroom/.gitattributes
  debug/registers_logs/bootroom/theirs.txt
  docs/TimerDiv.md
  gb-clock/src/tick.rs
  gb-dbg/src/dbg_interfaces.rs
  gb-timer/Cargo.toml
  gb-timer/src/lib.rs
  gb-timer/src/test_timer.rs
Labels: Bug, BUS

#451 fix - wrong number of cycles when handling interrupts
  gb-cpu/src/microcode/interrupts.rs
Labels: CPU

#457 Use sprite offset.
  gb-ppu/src/drawing/pixel_fetcher.rs
Labels: Bug, Display

#462 Feature/buff trace log
  src/logger.rs
Labels: Debug

#463 Feature/rework cpu log
  README.md
  gb-cpu/Cargo.toml
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/fetch_cb.rs
  gb-cpu/src/microcode/read.rs
Labels: Debug

#458 Correctly offset window.
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#467 Bugfix/stat ppu register endianess
  gb-ppu/src/registers/lcd/stat.rs
Labels: Bug, Display

#470 Bugfix/sprite overflow operations
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/sprite.rs
Labels: Bug, Display

#472 Bugfix/background smooth scrolling
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#475 Feature/cgb color io reg
  Cargo.toml
  README.md
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-cpu/Cargo.toml
  gb-cpu/src/builder.rs
  gb-cpu/src/cpu.rs
  gb-cpu/src/interrupt_flags.rs
  gb-cpu/src/io_registers.rs
  gb-cpu/src/lib.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/state.rs
  gb-dbg/Cargo.toml
  gb-dbg/src/dbg_interfaces.rs
  src/context.rs
Labels: BUS
