Repository Ragarnoy/GBMU, pull requests merged in 2021-08, with the labels that each got.

#5 Feature/opcode v2
  .vscode/launch.json
  Cargo.lock
  README.md
  gb-lcd/src/error.rs
  gb-lcd/src/lib.rs
  gb-lcd/src/render.rs
  gb-lcd/src/window.rs
  gb-roms/Cargo.toml
  gb-roms/examples/disas.rs
  gb-roms/examples/opcode_decompose.rs
  gb-roms/src/lib.rs
  gb-roms/src/opcode.rs
  gb-roms/src/opcode/error.rs
  gb-roms/src/opcode/list.rs
  gb-roms/src/opcode/register.rs
  src/main.rs
Labels: CPU, ROM

#7 Add github action
  .github/workflows/rust.yml
  README.md
Labels: CI

#29 correct github action cargo test
  .github/workflows/rust.yml
Labels: Bug, CI

#30 Correct github action caching
  .github/workflows/rust.yml
  Cargo.toml
Labels: Bug, CI

#35 Remove clippy warning.
  gb-lcd/src/lib.rs
  gb-lcd/src/render.rs
  gb-lcd/src/window.rs
  gb-ppu/src/lib.rs
  src/main.rs
Labels: Bug, CI

#31 Feature/add clippy to ci
  .github/workflows/rust.yml
  gb-roms/src/header/license_code.rs
Labels: CI

#20 Feature/simple address bus
  gb-cpu/src/address_bus.rs
Labels: CPU

#37 Feature/read pixels from tile data
  Cargo.lock
  gb-lcd/src/lib.rs
  gb-lcd/src/render.frag
  gb-lcd/src/render.rs
  gb-lcd/src/shader.rs
  gb-ppu/Cargo.toml
  gb-ppu/examples/memory dumps/Legend_of_Zelda_link_Awaking.dmp
  gb-ppu/examples/memory dumps/Pokemon_Bleue.dmp
  gb-ppu/examples/memory dumps/Super_Mario_Land.dmp
  gb-ppu/examples/tilesheet_viewer.rs
  gb-ppu/src/error.rs
  gb-ppu/src/lib.rs
  gb-ppu/src/memory.rs
  gb-ppu/src/memory/vram.rs
  src/main.rs
Labels: Display

#38 Add missing file extension when selecting a file.
  src/main.rs
Labels: Bug

#42 Feature/mbc5 controller
  gb-cpu/src/address_bus.rs
  gb-roms/src/controllers.rs
  gb-roms/src/controllers/mbc5.rs
Labels: ROM

#51 feature/bus trait
  gb-cpu/src/bus.rs
  gb-cpu/src/lib.rs
Labels: CPU, Architecture

#44 Feature/dgb (Debugger crate naive implementation)
  .github/workflows/rust.yml
  .idea/.gitignore
  .idea/GBMU.iml
  .idea/modules.xml
  .idea/vcs.xml
  Cargo.lock
  Cargo.toml
  gb-dbg/Cargo.toml
  gb-dbg/examples/debugger.rs
  gb-dbg/src/app.rs
  gb-dbg/src/disassembler.rs
  gb-dbg/src/flow_control.rs
  gb-dbg/src/lib.rs
  gb-dbg/src/memory.rs
  src/main.rs
Labels: Debug

#62 Bugfix/render incorrect
  Cargo.toml
  gb-lcd/Cargo.toml
  gb-lcd/src/render.rs
  gb-lcd/src/window.rs
  gb-ppu/examples/tilesheet_viewer.rs
  gb-ppu/src/lib.rs
  src/main.rs
Labels: Bug, Display

#61 Feature/add appimage packaging
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  assets/gbmu-512x512.png
  assets/gbmu.metainfo.xml
  packaging/linux/appimage/AppImageBuilder.yml
  packaging/linux/appimage/Dockerfile
Labels: Packaging

#60 add interface for basic address
  gb-bus/src/address.rs
  gb-bus/src/address_bus.rs
  gb-bus/src/address_bus/error.rs
  gb-bus/src/area.rs
  gb-bus/src/constant.rs
  gb-bus/src/error.rs
  gb-bus/src/file_operation.rs
  gb-bus/src/generic/chardev.rs
  gb-bus/src/generic/random.rs
  gb-bus/src/lib.rs
  gb-roms/src/controllers/mbc1.rs
  gb-roms/src/controllers/mbc5.rs
  gb-roms/src/controllers/rom_only.rs
Labels: Architecture
