Repository Ragarnoy/GBMU, pull requests merged in 2022-01, with the labels that each got.

#456 Feature/debug render invert color
  gb-ppu/examples/objects_viewer.rs
  gb-ppu/src/drawing/pixel_fifo.rs
  gb-ppu/src/ppu.rs
  src/context.rs
  src/event.rs
  src/main.rs
  src/ui.rs
  src/windows.rs
Labels: Display, Debug

#409 add feature to use the joypad in toggle mode
  gb-joypad/Cargo.toml
  gb-joypad/src/joypad.rs
Labels: Inputs

#466 use a mask to toggle unused field in interrupt enable/flag
  gb-cpu/src/io_registers.rs
Labels: CPU

#481 Bugfix/logger not logging
  Cargo.toml
  src/logger.rs
Labels: Bug, Debug

#480 Feature/rework address passtrough
  gb-bus/src/address.rs
  gb-bus/src/address_bus.rs
  gb-bus/src/error.rs
  gb-bus/src/file_operation.rs
  gb-bus/src/generic/chardev.rs
  gb-bus/src/generic/panic.rs
  gb-bus/src/generic/random.rs
  gb-bus/src/generic/simple.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/lib.rs
  gb-bus/src/lock.rs
  gb-bus/src/working_ram.rs
  gb-cpu/src/io_registers.rs
  gb-dma/src/lib.rs
  gb-joypad/src/joypad.rs
  gb-ppu/src/memory/ppu_mem.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/ppu_registers.rs
  gb-ppu/src/test_tools.rs
  gb-roms/src/controllers.rs
  gb-roms/src/controllers/bios.rs
  gb-roms/src/controllers/bios_wrapper.rs
  gb-roms/src/controllers/mbc1.rs
  gb-roms/src/controllers/mbc2.rs
  gb-roms/src/controllers/mbc3.rs
  gb-roms/src/controllers/mbc5.rs
  gb-roms/src/controllers/rom_only.rs
  gb-timer/src/lib.rs
Labels: BUS

#483 Feature/impl stop opcode
  gb-cpu/src/constant.rs
  gb-cpu/src/io_registers.rs
  gb-cpu/src/lib.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/interrupts.rs
Labels: CPU, Opcode

#484 Bugfix/build script bios
  gb-roms/build.rs
Labels: Bug, Bios

#398 Bugfix/ppu run lcd disabled
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#487 reduce the size of `draw_egui` using macro
  src/ui.rs
Labels: GUI, refactor

#485 Feature/customizable io reg bus
  gb-bus/src/address_bus.rs
  gb-bus/src/area.rs
  gb-bus/src/constant.rs
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/io_reg_constant.rs
  gb-bus/src/io_reg_constant_color.rs
  gb-bus/src/lib.rs
  gb-cpu/src/io_registers.rs
  gb-dma/src/lib.rs
  gb-joypad/src/joypad.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/lcd/control.rs
  gb-ppu/src/registers/lcd/palettes_mono.rs
  gb-ppu/src/registers/lcd/scrolling.rs
  gb-ppu/src/registers/lcd/window_pos.rs
  gb-ppu/src/registers/ppu_registers.rs
  gb-ppu/src/test_tools.rs
  gb-roms/src/controllers/mbc5.rs
  gb-timer/src/lib.rs
  src/context.rs
Labels: BUS

#494 Don't fetch sprite if obj are disabled.
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#495 Fetch white pixel if bg/window are disabled.
  gb-ppu/src/drawing/pixel_fetcher.rs
Labels: Bug, Display

#496 Add priority flag into pixel.
  gb-ppu/src/drawing/pixel.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/sprite.rs
Labels: Bug, Display

#502 rework write error message
  gb-cpu/src/microcode/state.rs
Labels: Debug

#501 Ignore bit 0 for 8x16 sprites.
  gb-ppu/src/sprite.rs
Labels: Bug, Display

#503 Feature/map skipped audio reg
  gb-bus/src/error.rs
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-cpu/src/microcode/state.rs
  src/context.rs
Labels: Bug, BUS

#400 Run to next instruction
  Cargo.lock
  gb-cpu/src/microcode/controller.rs
  gb-dbg/Cargo.toml
  gb-dbg/examples/debug_eframe/main.rs
  gb-dbg/src/debugger.rs
  gb-dbg/src/debugger/flow_control.rs
  gb-dbg/src/until.rs
  src/context.rs
  src/main.rs
Labels: Debug, Opcode

#506 Bugfix/file dialog path macos
  Cargo.lock
  Cargo.toml
  src/context.rs
Labels: Bug, save

#508 Bugfix/window bg tile offset
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#509 Correct tile line offset.
  gb-ppu/src/drawing/pixel_fetcher.rs
Labels: Bug, Display

#510 log error for invalide breakpoint given as options
  gb-dbg/src/debugger/breakpoints.rs
Labels: Debug

#512 [rom header] keep license code inside result
  gb-roms/src/header.rs
  gb-roms/src/header/error.rs
Labels: ROM

#513 Feature/simple serial
  gb-bus/src/lib.rs
  gb-bus/src/serial.rs
  src/context.rs
Labels: Inputs

#522 reorder `cycle` button after `step`
  gb-dbg/src/debugger/flow_control.rs
Labels: Debug

#521 Bugfix/breakpoint expr
  gb-dbg/src/debugger/breakpoints.rs
  gb-dbg/src/debugger/breakpoints/test_parser.rs
Labels: Bug, Debug

#520 add feature to panic on unknow opcode
  gb-cpu/Cargo.toml
  gb-cpu/src/microcode/fetch.rs
Labels: CPU

#515 Bugfix/sprite left of viewport
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#523 Feature/debug fps
  Cargo.toml
  README.md
  gb-dbg/examples/debug_eframe/main.rs
  gb-dbg/src/debugger.rs
  gb-dbg/src/debugger/status_bar.rs
  src/main.rs
  src/time_frame.rs
Labels: Debug

#524 update native dialogue
  Cargo.lock
  src/context.rs
Labels: update

#94 Feature/unlock framerate
  gb-lcd/src/window.rs
  src/main.rs
Labels: Debug, GUI

#525 add missing line from previous fix.
  gb-ppu/src/drawing/pixel_fetcher.rs
Labels: Bug, Display

#504 Feature/mask joypad
  gb-joypad/src/joypad.rs
Labels: refactor

#530 Feature/rework save state mbcs
  gb-roms/src/controllers.rs
  gb-roms/src/controllers/generic.rs
  gb-roms/src/controllers/mbc1.rs
  gb-roms/src/controllers/mbc2.rs
  gb-roms/src/controllers/mbc3.rs
  gb-roms/src/controllers/mbc5.rs
  gb-roms/src/controllers/rom_only.rs
  gb-roms/src/controllers/save.rs
  src/context.rs
  src/main.rs
Labels: ROM, save

#531 change log level to trace
  gb-dbg/src/debugger/disassembler.rs
Labels: Debug

#527 Feature/save state cpu
  Cargo.lock
  Cargo.toml
  gb-bus/src/io_reg_bus.rs
  gb-cpu/Cargo.toml
  gb-cpu/src/builder.rs
  gb-cpu/src/cpu.rs
  gb-cpu/src/io_registers.rs
  gb-cpu/src/lib.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/registers.rs
  gb-cpu/tests/bdd.rs
  src/context.rs
Labels: save

#538 rename `Cpu` field from `interrupt_flags` => `io_regs`
  gb-cpu/src/builder.rs
  gb-cpu/src/cpu.rs
  src/context.rs
Labels: CPU, refactor

#545 Feature/bump egui 0.16
  Cargo.lock
  Cargo.toml
  gb-dbg/Cargo.toml
  gb-dbg/examples/debug_eframe/main.rs
  gb-dbg/src/debugger/breakpoints.rs
  gb-dbg/src/debugger/registers.rs
  gb-joypad/Cargo.toml
  gb-lcd/Cargo.toml
  gb-lcd/src/window.rs
  gb-ppu/Cargo.toml
  gb-ppu/examples/objects_viewer.rs
  gb-ppu/examples/tilemap_viewer.rs
  gb-ppu/examples/tilesheet_viewer.rs
  src/ui.rs
Labels: Display

#534 Feature/rework debugger
  Cargo.lock
  Cargo.toml
  gb-breakpoint/Cargo.toml
  gb-breakpoint/src/lib.rs
  gb-breakpoint/src/native.rs
  gb-breakpoint/src/operation.rs
  gb-breakpoint/src/parser.rs
  gb-breakpoint/src/register.rs
  gb-breakpoint/src/test_parser.rs
  gb-breakpoint/src/unary.rs
  gb-breakpoint/src/wrapper.rs
  gb-dbg/Cargo.toml
  gb-dbg/src/dbg_interfaces.rs
  gb-dbg/src/debugger/breakpoints.rs
  gb-dbg/src/debugger/breakpoints/breakpoint.rs
  gb-dbg/src/debugger/breakpoints/evaluation.rs
  gb-dbg/src/debugger/breakpoints/parser.rs
  gb-dbg/src/debugger/breakpoints/test_parser.rs
  src/context.rs
Labels: Debug

#532 Feature/improve fps display
  gb-dbg/src/debugger.rs
  gb-dbg/src/debugger/status_bar.rs
  src/main.rs
  src/ui.rs
Labels: Debug, GUI

#549 Feature/use u8 trailing zeros
  gb-cpu/src/microcode/interrupts.rs
Labels: CPU, refactor
