Repository Ragarnoy/GBMU, pull requests merged in 2022-04, with the labels that each got.

#607 Feature/sprite cgb attributes
  .gitignore
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/sprite.rs
Labels: Display, CGB

#608 Feature/bg win use color palette
  gb-ppu/src/drawing/bg_tile_attributes.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
Labels: Display, CGB

#601 Feature/opri
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/ppu_registers.rs
Labels: Display

#590 Use overflowing_add method to avoid overflow for PC reg
  gb-cpu/src/microcode/state.rs
Labels: Bug

#609 Feat/save state dma
  Cargo.lock
  Cargo.toml
  gb-dma/Cargo.toml
  gb-dma/src/dma.rs
  src/context.rs
Labels: save

#610 Feat/save state hdma
  gb-dma/src/hdma.rs
  src/context.rs
Labels: save

#615 Bugfix/map cgb ppu registers
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-ppu/src/color.rs
  src/context.rs
Labels: Display, CGB

#616 export configuration
  src/config.rs
  src/main.rs
Labels: refactor

#622 Fix/cgb bios mapping
  gb-dbg/src/dbg_interfaces.rs
  gb-roms/src/controllers.rs
  gb-roms/src/controllers/bios_wrapper.rs
  src/context.rs
Labels: Bug, Bios

#618 split context & game context
  .github/workflows/rust.yml
  src/context.rs
  src/game.rs
  src/game/save_state.rs
  src/game/utils.rs
  src/main.rs
Labels: refactor

#617 move constant to proper file
  src/constant.rs
  src/main.rs
Labels: refactor

#632 Feat/impl breakpoint
  src/context.rs
  src/context/debugger.rs
  src/game.rs
  src/main.rs
  src/ui.rs
  src/windows.rs
Labels: GUI

#625 update rust requirement to `1.60`
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  src/game/utils.rs
Labels: update

#623 Bugfix/fix sprite cgb
  .gitignore
  gb-ppu/src/drawing/pixel.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/drawing/pixel_fifo.rs
  gb-ppu/src/memory/oam.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/lcd/palette_ref.rs
  gb-ppu/src/sprite.rs
  src/config.rs
  src/game.rs
  src/main.rs
  src/ui.rs
Labels: Display, CGB

#634 Set cpu register for CGB mode
  gb-cpu/src/registers.rs
  src/game.rs
Labels: CPU, Bios

#635 In fast mode, the frame finished wasn't checked every second cycles
  src/game.rs
Labels: CPU, CGB

#637 Split cycles macro in 2.
  gb-clock/src/clock.rs
  src/game.rs
Labels: Bug

#636 fix double speed according to doc
  gb-cpu/src/io_registers.rs
Labels: Bug, CPU
