Repository Ragarnoy/GBMU, pull requests merged in 2022-05, with the labels that each got.

#643 If write 0, set to bank 1 instead
  gb-bus/src/working_ram.rs
Labels: CGB

#640 Automatically exit halt mode after 0x2000 t-cycles when coming from a…
  gb-cpu/src/lib.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/interrupts.rs
Labels: CPU

#626 Feature/migrate pixels
  .vscode/launch.json
  Cargo.lock
  Cargo.toml
  gb-dbg/src/lib.rs
  gb-joypad/Cargo.toml
  gb-joypad/src/config.rs
  gb-joypad/src/input.rs
  gb-joypad/src/joypad.rs
  gb-joypad/src/lib.rs
  gb-lcd/Cargo.toml
  gb-lcd/src/context.rs
  gb-lcd/src/lib.rs
  gb-lcd/src/pixels.rs
  gb-lcd/src/render.rs
  gb-lcd/src/state.rs
  gb-lcd/src/window.rs
  gb-ppu/Cargo.toml
  gb-ppu/examples/objects_viewer.rs
  gb-ppu/src/lib.rs
  gb-ppu/src/ppu.rs
  src/constant.rs
  src/context.rs
  src/context/debugger.rs
  src/context/keybindings.rs
  src/custom_event.rs
  src/game.rs
  src/game/utils.rs
  src/image.rs
  src/main.rs
  src/path.rs
  src/time_frame.rs
  src/ui.rs
  src/ui/file.rs
  src/ui/settings.rs
  src/ui/tools.rs
  src/windows.rs
  todo
Labels: refactor, update

#645 Fix sprite disappearing Mystic Quest
  gb-ppu/src/ppu.rs
Labels: Display

#663 Manually drop game.
  src/main.rs
Labels: Bug

#665 Feature/remove feature cgb
  .lsp.config.json
  Cargo.toml
  README.md
  gb-bus/Cargo.toml
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/io_reg_constant.rs
  gb-bus/src/serial.rs
  gb-cpu/Cargo.toml
  gb-cpu/src/builder.rs
  gb-cpu/src/cpu.rs
  gb-cpu/src/io_registers.rs
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/interrupts.rs
  gb-dbg/Cargo.toml
  gb-dbg/src/dbg_interfaces.rs
  gb-ppu/Cargo.toml
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/ppu_registers.rs
  src/config.rs
  src/context.rs
  src/custom_event.rs
  src/game.rs
  src/main.rs
  src/ui.rs
  src/ui/settings.rs
Labels: QoL

#604 APU - Channels 1, 2 and 3
  Cargo.lock
  Cargo.toml
  gb-apu/Cargo.toml
  gb-apu/src/apu.rs
  gb-apu/src/channel.rs
  gb-apu/src/channel/duty.rs
  gb-apu/src/channel/length_counter.rs
  gb-apu/src/channel/sound_channel.rs
  gb-apu/src/channel/sweep.rs
  gb-apu/src/channel/timer.rs
  gb-apu/src/channel/volume_envelope.rs
  gb-apu/src/channel/wave_ram.rs
  gb-apu/src/control.rs
  gb-apu/src/control/frame_sequencer.rs
  gb-apu/src/lib.rs
  gb-bus/src/io_reg_bus.rs
  src/game.rs
Labels: Sound

#672 remove duplicate register
  gb-dbg/src/dbg_interfaces.rs
  src/game.rs
Labels: Sound

#678 bugfix/save pixel for menu bar
  src/ui.rs
Labels: Bug

#647 Apu noise
  gb-apu/src/apu.rs
  gb-apu/src/channel.rs
  gb-apu/src/channel/lfsr.rs
  gb-apu/src/channel/sound_channel.rs
  gb-apu/src/channel/timer.rs
  gb-apu/src/lib.rs
Labels: Sound

#681 Fix - APU behaviour changes depending on the output device config
  gb-apu/src/apu.rs
  gb-apu/src/lib.rs
  src/game.rs
Labels: Sound

#673 Feature/register sound blargg
  gb-apu/src/apu.rs
  gb-apu/src/channel/sound_channel.rs
  gb-apu/src/channel/wave_ram.rs
  gb-apu/src/lib.rs
Labels: Sound

#688 Line 153 count as LY 0.
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/ppu.rs
Labels: Bug, Display

#685 Feature/ppu tools for pixels
  gb-ppu/src/lib.rs
  gb-ppu/src/ppu.rs
  src/context.rs
  src/context/ppu_tool.rs
  src/main.rs
  src/ui/tools.rs
  src/windows.rs
Labels: Display, Debug

#692 increase main window init size
  src/main.rs
Labels: QoL

#694 Feat/rework fps
  .vscode/settings.json
  Cargo.toml
  README.md
  gb-clock/examples/uncapped.rs
  gb-dbg/examples/debug_eframe/game.rs
  src/context.rs
  src/main.rs
  src/time_frame.rs
  src/ui.rs
  src/ui/fps.rs
Labels: QoL

#697 Ly equal 0 at line 153 for every mode.
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/ppu.rs
Labels: Bug

#698 bugfix/fix hdma
  gb-dma/src/hdma.rs
Labels: Bug

#700 fix game not paused when starting the debugger in the cli
  src/context.rs
  src/main.rs
Labels: Bug, QoL

#707 Control volume in settings menu.
  .idea/GBMU.iml
  gb-apu/src/apu.rs
  src/ui.rs
  src/ui/fps.rs
  src/ui/volume.rs
Labels: GUI

#709 Allow to use other sample rates to be more flexible (44,1 KHz and 48 KHz)
  gb-apu/src/apu.rs
  gb-apu/src/lib.rs
Labels: Sound

#717 Feature/color palette lock
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/lcd/palettes_cgb.rs
Labels: Display, CGB
