Repository Ragarnoy/GBMU, pull requests merged in 2022-03, with the labels that each got.

#582 Feature/add toggle mode cli
  Cargo.toml
  src/context.rs
  src/main.rs
Labels: CGB

#585 Feature/add toggle mode gui
  src/context.rs
  src/custom_event.rs
  src/main.rs
  src/ui.rs
Labels: GUI

#562 Bugfix/correct timing
  gb-bus/src/serial.rs
  gb-cpu/src/microcode/fetch.rs
  gb-timer/src/lib.rs
  gb-timer/src/test_timer.rs
  src/context.rs
Labels: Bug, CPU, BUS

#592 Bugfix/ppu disabled reset
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/ppu_registers.rs
  src/context.rs
Labels: Bug

#595 Fix default value for vbk.
  gb-ppu/src/memory/vram.rs
  gb-ppu/src/registers/lcd.rs
Labels: Bug, Display

#591 Feature/cgb color palettes
  gb-ppu/src/color.rs
  gb-ppu/src/drawing/pixel.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/drawing/pixel_fifo.rs
  gb-ppu/src/registers.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/lcd/palette_ref.rs
  gb-ppu/src/registers/lcd/palettes_cgb.rs
  gb-ppu/src/registers/lcd/palettes_mono.rs
  gb-ppu/src/registers/palette.rs
  gb-ppu/src/registers/ppu_registers.rs
  gb-ppu/src/sprite.rs
Labels: Display

#597 Feature/hdma
  Cargo.lock
  gb-bus/src/io_reg_area.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/io_reg_constant.rs
  gb-cpu/src/cpu.rs
  gb-dma/Cargo.toml
  gb-dma/src/dma.rs
  gb-dma/src/hdma.rs
  gb-dma/src/lib.rs
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/lib.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/ppu_registers.rs
  src/context.rs
Labels: DMA
