Repository Ragarnoy/GBMU, pull requests merged in 2022-02, with the labels that each got.

#555 Test bdd for opcode duration + cycles correction
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/fetch.rs
  gb-cpu/src/microcode/interrupts.rs
  gb-cpu/tests/bdd.rs
  gb-cpu/tests/features/unprefixed_duration.feature
Labels: CPU, Test

#556 Feature/bdd prefixed opcodes duration
  gb-cpu/src/microcode/fetch_cb.rs
  gb-cpu/src/microcode/opcode_cb.rs
  gb-cpu/tests/bdd.rs
  gb-cpu/tests/features/cb_prefixed_duration.feature
Labels: CPU, Test

#558 Bugfix/ppu underflow sprite fetch
  gb-ppu/src/ppu.rs
Labels: Bug

#560 Wider debugger to avoid overlapping sections
  gb-dbg/src/debugger.rs
  gb-dbg/src/lib.rs
Labels: Debug

#561 Feature/improve serial
  gb-bus/src/serial.rs
Labels: Display

#565 Remove gtk3 dependencie from readme instruction.
  README.md
Labels: Documentation

#540 Feature/save state wram
  Cargo.lock
  Cargo.toml
  gb-bus/Cargo.toml
  gb-bus/src/generic.rs
  gb-bus/src/generic/bankable.rs
  gb-bus/src/generic/bankable_dyn.rs
  gb-bus/src/io_reg_bus.rs
  gb-bus/src/lib.rs
  gb-bus/src/working_ram.rs
  src/context.rs
Labels: save, BUS

#543 Feature/save state hram
  gb-bus/src/generic/simple.rs
  src/context.rs
Labels: save

#551 Feature/ir reg bus color
  src/context.rs
Labels: BUS

#554 Feature/save state timer div
  Cargo.lock
  Cargo.toml
  gb-timer/Cargo.toml
  gb-timer/src/lib.rs
  src/context.rs
Labels: save

#548 Feature/double speed cpu
  gb-cpu/src/io_registers.rs
  gb-cpu/src/microcode/interrupts.rs
  src/context.rs
Labels: CPU, BUS

#573 initialize working ram
  gb-bus/src/working_ram.rs
Labels: Bug, BUS

#552 Feature/serialize ppu
  Cargo.lock
  gb-bus/src/lock.rs
  gb-ppu/Cargo.toml
  gb-ppu/src/drawing.rs
  gb-ppu/src/drawing/mode.rs
  gb-ppu/src/drawing/pixel.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/drawing/pixel_fifo.rs
  gb-ppu/src/drawing/state.rs
  gb-ppu/src/memory/oam.rs
  gb-ppu/src/memory/vram.rs
  gb-ppu/src/memory/vram/de_ser.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/ppu/de_ser.rs
  gb-ppu/src/registers.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/lcd/control.rs
  gb-ppu/src/registers/lcd/palettes_mono.rs
  gb-ppu/src/registers/lcd/scrolling.rs
  gb-ppu/src/registers/lcd/stat.rs
  gb-ppu/src/registers/lcd/window_pos.rs
  gb-ppu/src/registers/palette.rs
  gb-ppu/src/sprite.rs
Labels: save

#578 Feature/vbk ppu register
  gb-ppu/src/memory/ppu_mem.rs
  gb-ppu/src/memory/vram.rs
  gb-ppu/src/ppu.rs
  gb-ppu/src/registers/lcd.rs
  gb-ppu/src/registers/ppu_registers.rs
Labels: Display, CGB

#576 Feature/bg map attributes
  gb-ppu/src/drawing.rs
  gb-ppu/src/drawing/bg_tile_attributes.rs
  gb-ppu/src/drawing/pixel_fetcher.rs
  gb-ppu/src/memory.rs
  gb-ppu/src/ppu.rs
Labels: Display, CGB

#579 Add timer registers to the `registers_logs` feature
  Cargo.toml
  gb-cpu/Cargo.toml
  gb-cpu/src/microcode/controller.rs
  gb-cpu/src/microcode/state.rs
  gb-cpu/src/registers.rs
  gb-timer/src/lib.rs
  src/context.rs
Labels: Debug

#574 add readonly device
  gb-bus/src/generic.rs
  gb-bus/src/generic/readonly.rs
Labels: BUS
